### ISSUE TITLE
Yin color code and Zero voice codes

### ISSUE THREAD

**Issue by nmbook** [the-database/trails-in-the-database#1]
Voiced lines for characters with color (specifically Yin), it appears the first box of opcodes that are colored are not linked.

Generally in Zero's scenario, we would start boxes with the `#...V` code (before the color code) because of how our matching functioned, which could potentially lead to weird constructs of # code, color code, # code.

Visible examples:
![](https://cdn.discordapp.com/attachments/665464049475125258/734499668058177727/unknown.png)
![](https://cdn.discordapp.com/attachments/665464049475125258/734501576760360991/unknown.png)
![](https://cdn.discordapp.com/attachments/665464049475125258/734501469830774794/unknown.png)

**Comment by the-database** [comment]
This was affecting both Crossbell scripts. It has been fixed by 458bb874cca9142e74f8effa0371383706bc8c08
